FROM golang:1.26-alpine

WORKDIR /app

# Install air for hot-reloading
RUN go install github.com/air-verse/air@latest

# Install dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the code
COPY . .

# Expose port
EXPOSE 8080

# Run air
CMD ["air", "-c", ".air.toml"]
