apiVersion: v1
kind: ConfigMap
metadata:
  name: hookord-config
data:
  LOG_LEVEL: "info"
  APP_ENV: "kubernetes"
  PORT: "8080"
---
apiVersion: v1
kind: Secret
metadata:
  name: hookord-secrets
type: Opaque
data:
  # Base64 encoded values (exemplo)
  DISCORD_TOKEN: "MTEyMjMzNDQ1NTY2Nzc4ODk5MA==" # Exemplo
  GITHUB_SECRET: "c2VjcmV0LWtleQ==" # Exemplo
  REDIS_URL: "cmVkaXM6Ly9yZWRpczp6ZW5vQHJlZGlzLXNlcnZpY2U6NjM3OQ==" # Exemplo
