apiVersion: apps/v1
kind: Deployment
metadata:
  name: hookord
  labels:
    app: hookord
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hookord
  template:
    metadata:
      labels:
        app: hookord
    spec:
      containers:
        - name: hookord
          image: ghcr.io/juliofiliizzola/hookord:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          