app:
  name: "hookord"
  version: "v0.0.1"

http:
  port: "8080"

logging:
  level: "info"

github:
  webhook_secret: "sha256=SEU_GITHUB_WEBHOOK_SECRET_AQUI"
  allowed_repos:
    - "sua-org/seu-repo"
    - "seuuser/seu-repo-pessoal"

discord:
  webhook_url: "https://discord.com/api/webhooks/SEU_WEBHOOK_ID/SEU_WEBHOOK_TOKEN"
